apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-7yvh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-thcp-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-7yvh@sha256:e2f4adedc773d3458f87131b29f94dcfe7999bc2da49e804e3e5eff31a269569
        name: my-python
        resources: {}
status: {}
